---
- hosts: 192.168.88.163
  remote_user: root
  become_user: root
  vars_files:
  - vars/common_config.yaml
  # - vars/group_replication.yaml

  tasks:
  - name: hello world
    when: ansible_distribution_major_version == "6"
    debug: 
      msg: "echo {{ansible_distribution_major_version}}"